name: YT-DLP

on:
  workflow_dispatch: # 手動実行用

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cp -fr emsdk/ emsdk2/
      - name: Install yt-dlp
        run: |
          rm -fdr yt-dlp
          curl -v -L https://github.com/yt-dlp/yt-dlp/archive/refs/heads/master.zip -o yt-dlpv2.zip
          ls -l yt-dlpv2.zip
          unzip -t yt-dlpv2.zip
          unzip -o yt-dlpv2.zip
          
      - name: Cleanup and Commit
        run: |
          # 1. まずGitのユーザー設定を確実に行う
          git config --global user.name "Gemini-Bot"
          git config --global user.email "bot@example.com"
          
          # 2. セキュリティで弾かれた特定のファイルだけを削除対象にする
          # 全てのPythonファイルを消すと探検隊の武器がなくなってしまうからな！
          find . -name "shahid.py" -exec git rm -f {} \;
          
          # 3. .gitignoreに追記
          echo "**/shahid.py" >> .gitignore
          
          # 4. 追加とコミット
          git add .
          # 何も変更がない場合にエラーにならないよう || true を付ける
          git commit -m "yt-dlp cleaned ✨" || true
          
          # 5. プッシュ！
          git push
