name: WASM Factory Build

on:
  workflow_dispatch: # 手動実行用

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cp -fr emsdk/ emsdk2/
      - name: Install yt-dlp
        run: |
          git clone https://github.com/yt-dlp/yt-dlp.git
          cp -fr yt-dlp/ ytdlp/
      - name: Cleanup and Commit
        run: |
          git config user.name "Gemini-Bot"
          git config user.email "bot@example.com"
          git add .
          git commit -m "yt-dlp cleaned ✨"
          git push
